/* DO NOT EDIT: generated by tools/generate_proto_enums.py. */
/* proto/volvoxai.proto SHA-256: 9e981ca1d49b04ead708acf667c0a94d323edfbed400d6faf74ec29a58f8df89 */
#ifndef VOLVOXAI_ENUMS_H
#define VOLVOXAI_ENUMS_H

#include <stddef.h>
#include <stdint.h>

typedef int32_t VxStatus;
enum {
    VX_STATUS_OK = 0,
    VX_STATUS_INVALID_ARGUMENT = -1,
    VX_STATUS_OUT_OF_MEMORY = -2,
    VX_STATUS_HANDLE_DISPOSED = -3,
    VX_STATUS_IO_ERROR = -4,
    VX_STATUS_INVALID_GRAPH = -5,
    VX_STATUS_BACKEND_UNAVAILABLE = -6,
    VX_STATUS_BACKEND_UNSUPPORTED = -7,
    VX_STATUS_BACKEND_REQUIRED = -8,
    VX_STATUS_OPERATOR_FALLBACK_FORBIDDEN = -9,
    VX_STATUS_EXECUTION_FAILED = -10,
    VX_STATUS_RESULT_DISPOSED = -11,
    VX_STATUS_DEVICE_LOST = -12,
    VX_STATUS_ABI_UNSUPPORTED = -13,
    VX_STATUS_NOT_FOUND = -14,
    VX_STATUS_BUFFER_TOO_SMALL = -15,
    VX_STATUS_INTERNAL = -16,
    VX_STATUS_REVISION_CONFLICT = -17,
    VX_STATUS_BUSY = -18,
    VX_STATUS_OVERLOADED = -19,
    VX_STATUS_CANCELLED = -20,
    VX_STATUS_DEADLINE_EXCEEDED = -21,
    VX_STATUS_SUPERSEDED = -22,
    VX_STATUS_SESSION_RESET_REQUIRED = -23
};

typedef int32_t VxStage;
enum {
    VX_STAGE_NONE = 0,
    VX_STAGE_RUNTIME_CREATE = 1,
    VX_STAGE_MODEL_LOAD = 2,
    VX_STAGE_COMPILE = 3,
    VX_STAGE_CONTEXT_CREATE = 4,
    VX_STAGE_INPUT = 5,
    VX_STAGE_EXECUTE = 6,
    VX_STAGE_READBACK = 7,
    VX_STAGE_CLOSE = 8,
    VX_STAGE_DECODE = 9,
    VX_STAGE_ADAPTER = 10
};

typedef int32_t VxDataType;
enum {
    VX_DTYPE_UNSPECIFIED = 0,
    VX_DTYPE_BOOL = 1,
    VX_DTYPE_F4 = 2,
    VX_DTYPE_F6_E2M3 = 3,
    VX_DTYPE_F6_E3M2 = 4,
    VX_DTYPE_U8 = 5,
    VX_DTYPE_I8 = 6,
    VX_DTYPE_F8_E5M2 = 7,
    VX_DTYPE_F8_E4M3 = 8,
    VX_DTYPE_F8_E8M0 = 9,
    VX_DTYPE_F8_E4M3FNUZ = 10,
    VX_DTYPE_F8_E5M2FNUZ = 11,
    VX_DTYPE_I16 = 12,
    VX_DTYPE_U16 = 13,
    VX_DTYPE_F16 = 14,
    VX_DTYPE_BF16 = 15,
    VX_DTYPE_I32 = 16,
    VX_DTYPE_U32 = 17,
    VX_DTYPE_F32 = 18,
    VX_DTYPE_C64 = 19,
    VX_DTYPE_F64 = 20,
    VX_DTYPE_I64 = 21,
    VX_DTYPE_U64 = 22
};

typedef int32_t VxOperatorKind;
enum {
    VX_OP_UNSPECIFIED = 0,
    VX_OP_MATMUL = 1000,
    VX_OP_LINEAR = 1001,
    VX_OP_Q_LINEAR = 1002,
    VX_OP_BATCH_MATMUL = 1003,
    VX_OP_Q_BATCH_MATMUL = 1004,
    VX_OP_Q_GEMM = 1005,
    VX_OP_GEMM = 1006,
    VX_OP_Q_MATMUL = 1007,
    VX_OP_MOE_ROUTER = 1010,
    VX_OP_MOE_LINEAR = 1011,
    VX_OP_SDPA = 1020,
    VX_OP_Q_SDPA = 1021,
    VX_OP_CROSS_SDPA = 1022,
    VX_OP_CROSS_ATTENTION = 1023,
    VX_OP_LAYER_NORM = 2000,
    VX_OP_Q_LAYER_NORM = 2001,
    VX_OP_GROUP_NORM = 2002,
    VX_OP_Q_GROUP_NORM = 2003,
    VX_OP_RMS_NORM = 2004,
    VX_OP_BATCH_NORM_2D = 2005,
    VX_OP_CONV_2D = 3000,
    VX_OP_Q_CONV_2D = 3001,
    VX_OP_CONV_1D = 3002,
    VX_OP_CONV_TRANSPOSE_2D = 3003,
    VX_OP_MAX_POOL_2D = 3010,
    VX_OP_AVERAGE_POOL_2D = 3011,
    VX_OP_GLOBAL_AVERAGE_POOL = 3012,
    VX_OP_RESIZE = 3020,
    VX_OP_INTERPOLATE_1D = 3021,
    VX_OP_RESIZE_NEAREST_2D = 3022,
    VX_OP_UPSAMPLE_NEAREST_2D = 3023,
    VX_OP_RELU = 4000,
    VX_OP_LEAKY_RELU = 4001,
    VX_OP_PRELU = 4002,
    VX_OP_GELU = 4003,
    VX_OP_Q_GELU = 4004,
    VX_OP_SILU = 4005,
    VX_OP_Q_SILU = 4006,
    VX_OP_SIGMOID = 4007,
    VX_OP_HARD_SWISH = 4008,
    VX_OP_HARD_SIGMOID = 4009,
    VX_OP_TANH = 4010,
    VX_OP_SIN = 4011,
    VX_OP_COS = 4012,
    VX_OP_CLIP = 4013,
    VX_OP_ADD = 5000,
    VX_OP_Q_ADD = 5001,
    VX_OP_SUB = 5002,
    VX_OP_MUL = 5003,
    VX_OP_DIV = 5004,
    VX_OP_SOFTMAX = 5010,
    VX_OP_LOG_SOFTMAX = 5011,
    VX_OP_REDUCE_SUM = 5012,
    VX_OP_REDUCE_MEAN = 5013,
    VX_OP_Q_MASKED_MEAN = 5014,
    VX_OP_ARG_MAX = 5015,
    VX_OP_Q_ARG_MAX = 5016,
    VX_OP_EQUAL = 5020,
    VX_OP_GREATER_OR_EQUAL = 5021,
    VX_OP_NOT = 5022,
    VX_OP_WHERE = 5023,
    VX_OP_MASK = 5024,
    VX_OP_RESHAPE = 6000,
    VX_OP_FLATTEN = 6001,
    VX_OP_SQUEEZE = 6002,
    VX_OP_UNSQUEEZE = 6003,
    VX_OP_TRANSPOSE = 6004,
    VX_OP_CONCAT = 6005,
    VX_OP_SPLIT = 6006,
    VX_OP_SLICE = 6007,
    VX_OP_PAD = 6008,
    VX_OP_EXPAND = 6009,
    VX_OP_GATHER = 6010,
    VX_OP_GATHER_ELEMENTS = 6011,
    VX_OP_IDENTITY = 6012,
    VX_OP_BROADCAST = 6013,
    VX_OP_CONCAT2 = 6014,
    VX_OP_QUANTIZE_LINEAR = 7000,
    VX_OP_DEQUANTIZE_LINEAR = 7001,
    VX_OP_REQUANTIZE_LINEAR = 7002,
    VX_OP_CAST = 7003,
    VX_OP_EMBEDDING = 8000,
    VX_OP_Q_EMBEDDING = 8001,
    VX_OP_ROPE = 8002,
    VX_OP_SSM_SCAN = 8003,
    VX_OP_SELECTIVE_SCAN = 8004,
    VX_OP_NON_MAX_SUPPRESSION = 8010,
    VX_OP_SPATIAL_SOFTARGMAX_Y = 8011,
    VX_OP_MEAN_HEIGHT = 8012,
    VX_OP_PROFILE_X = 8013,
    VX_OP_PROFILE_Y = 8014,
    VX_OP_DROPOUT = 8020
};

typedef int32_t VxBackendPolicyMode;
enum {
    VX_BACKEND_PREFER = 0,
    VX_BACKEND_REQUIRE = 1
};

typedef int32_t VxOperatorFallback;
enum {
    VX_OPERATOR_FALLBACK_ALLOW = 0,
    VX_OPERATOR_FALLBACK_FORBID = 1
};

typedef int32_t VxMemoryLocation;
enum {
    VX_MEMORY_HOST = 0,
    VX_MEMORY_DEVICE = 1
};

typedef int32_t VxDecodeRowMode;
enum {
    VX_DECODE_ROW_DISABLED = 0,
    VX_DECODE_ROW_AUTO = 1,
    VX_DECODE_ROW_REQUIRED = 2
};

typedef int32_t VxExecutionMode;
enum {
    VX_EXECUTION_MODE_DIRECT = 0,
    VX_EXECUTION_MODE_SCHEDULED = 1
};

typedef int32_t VxMemorySpace;
enum {
    VX_MEMORY_SPACE_UNSPECIFIED = 0,
    VX_MEMORY_SPACE_HOST = 1,
    VX_MEMORY_SPACE_JS_HEAP = 2,
    VX_MEMORY_SPACE_JS_EXTERNAL = 3,
    VX_MEMORY_SPACE_JS_ARRAY_BUFFER = 4,
    VX_MEMORY_SPACE_WASM_LINEAR = 5,
    VX_MEMORY_SPACE_NATIVE_HEAP = 6,
    VX_MEMORY_SPACE_MAPPED_FILE = 7,
    VX_MEMORY_SPACE_DEVICE = 8,
    VX_MEMORY_SPACE_DEVICE_LOCAL = 9,
    VX_MEMORY_SPACE_HOST_VISIBLE_DEVICE = 10,
    VX_MEMORY_SPACE_UNIFIED = 11
};

typedef int32_t VxMemoryOwnerKind;
enum {
    VX_MEMORY_OWNER_UNSPECIFIED = 0,
    VX_MEMORY_OWNER_PROCESS = 1,
    VX_MEMORY_OWNER_RUNTIME = 2,
    VX_MEMORY_OWNER_MODEL = 3,
    VX_MEMORY_OWNER_COMPILED_MODEL = 4,
    VX_MEMORY_OWNER_EXECUTION_CONTEXT = 5,
    VX_MEMORY_OWNER_RESULT = 6,
    VX_MEMORY_OWNER_BACKEND_SHARED = 7
};

typedef int32_t VxMemoryResourceRole;
enum {
    VX_MEMORY_RESOURCE_ROLE_UNSPECIFIED = 0,
    VX_MEMORY_RESOURCE_ROLE_WEIGHTS = 1,
    VX_MEMORY_RESOURCE_ROLE_PACKED_WEIGHTS = 2,
    VX_MEMORY_RESOURCE_ROLE_INPUT = 3,
    VX_MEMORY_RESOURCE_ROLE_ACTIVATION = 4,
    VX_MEMORY_RESOURCE_ROLE_KV_CACHE = 5,
    VX_MEMORY_RESOURCE_ROLE_SCRATCH = 6,
    VX_MEMORY_RESOURCE_ROLE_RESULT_SNAPSHOT = 7,
    VX_MEMORY_RESOURCE_ROLE_ARENA = 8,
    VX_MEMORY_RESOURCE_ROLE_PLAN_CACHE = 9,
    VX_MEMORY_RESOURCE_ROLE_KERNEL_CACHE = 10,
    VX_MEMORY_RESOURCE_ROLE_METADATA = 11,
    VX_MEMORY_RESOURCE_ROLE_RUNTIME_OVERHEAD = 12,
    VX_MEMORY_RESOURCE_ROLE_ALLOCATOR_OVERHEAD = 13,
    VX_MEMORY_RESOURCE_ROLE_DRIVER_OVERHEAD = 14,
    VX_MEMORY_RESOURCE_ROLE_OTHER = 15
};

typedef int32_t VxMemoryBackingRelation;
enum {
    VX_MEMORY_BACKING_RELATION_UNSPECIFIED = 0,
    VX_MEMORY_BACKING_RELATION_INDEPENDENT = 1,
    VX_MEMORY_BACKING_RELATION_ALIAS = 2,
    VX_MEMORY_BACKING_RELATION_SUBALLOCATION = 3
};

typedef int32_t VxMemoryBoundKind;
enum {
    VX_MEMORY_BOUND_UNSPECIFIED = 0,
    VX_MEMORY_BOUND_MAXIMUM_TENSOR = 1,
    VX_MEMORY_BOUND_CONTEXT_CAPACITY = 2,
    VX_MEMORY_BOUND_ORDINARY_RESIDENT = 3,
    VX_MEMORY_BOUND_DECODE_RESIDENT = 4
};

typedef int32_t VxMemorySnapshotPoint;
enum {
    VX_MEMORY_SNAPSHOT_UNSPECIFIED = 0,
    VX_MEMORY_SNAPSHOT_BEFORE = 1,
    VX_MEMORY_SNAPSHOT_AFTER = 2,
    VX_MEMORY_SNAPSHOT_PERIODIC = 3,
    VX_MEMORY_SNAPSHOT_FAILURE = 4
};

typedef int32_t VxMemoryMetric;
enum {
    VX_MEMORY_METRIC_UNSPECIFIED = 0,
    VX_MEMORY_METRIC_LOGICAL = 1,
    VX_MEMORY_METRIC_LIVE = 2,
    VX_MEMORY_METRIC_RESERVED = 3,
    VX_MEMORY_METRIC_CAPACITY = 4,
    VX_MEMORY_METRIC_LOGICAL_HIGH_WATER = 5,
    VX_MEMORY_METRIC_LIVE_HIGH_WATER = 6,
    VX_MEMORY_METRIC_RESERVED_HIGH_WATER = 7,
    VX_MEMORY_METRIC_CAPACITY_HIGH_WATER = 8,
    VX_MEMORY_METRIC_CUMULATIVE_ALLOCATED = 9
};

typedef int32_t VxMemoryEvidenceSource;
enum {
    VX_MEMORY_EVIDENCE_SOURCE_UNSPECIFIED = 0,
    VX_MEMORY_EVIDENCE_SOURCE_ALLOCATOR_COUNTER = 1,
    VX_MEMORY_EVIDENCE_SOURCE_RUNTIME_COUNTER = 2,
    VX_MEMORY_EVIDENCE_SOURCE_API_REQUEST = 3,
    VX_MEMORY_EVIDENCE_SOURCE_OS_SAMPLER = 4,
    VX_MEMORY_EVIDENCE_SOURCE_DRIVER_SAMPLER = 5
};

typedef int32_t VxMemoryValueRelation;
enum {
    VX_MEMORY_VALUE_RELATION_UNSPECIFIED = 0,
    VX_MEMORY_VALUE_RELATION_EXACT = 1,
    VX_MEMORY_VALUE_RELATION_UPPER_BOUND = 2,
    VX_MEMORY_VALUE_RELATION_LOWER_BOUND = 3,
    VX_MEMORY_VALUE_RELATION_REQUESTED = 4,
    VX_MEMORY_VALUE_RELATION_ESTIMATED = 5,
    VX_MEMORY_VALUE_RELATION_UNAVAILABLE = 6
};

typedef int32_t VxMemoryTemporalCoverage;
enum {
    VX_MEMORY_TEMPORAL_COVERAGE_UNSPECIFIED = 0,
    VX_MEMORY_TEMPORAL_COVERAGE_INSTANT = 1,
    VX_MEMORY_TEMPORAL_COVERAGE_OPERATION_WINDOW = 2,
    VX_MEMORY_TEMPORAL_COVERAGE_RESOURCE_LIFETIME = 3,
    VX_MEMORY_TEMPORAL_COVERAGE_CAPTURE_WINDOW = 4,
    VX_MEMORY_TEMPORAL_COVERAGE_PROCESS_LIFETIME = 5,
    VX_MEMORY_TEMPORAL_COVERAGE_SAMPLED_WINDOW = 6
};

typedef int32_t VxMemoryEnvelopeKind;
enum {
    VX_MEMORY_ENVELOPE_UNSPECIFIED = 0,
    VX_MEMORY_ENVELOPE_PROCESS_RSS = 1,
    VX_MEMORY_ENVELOPE_PROCESS_PEAK_RSS = 2,
    VX_MEMORY_ENVELOPE_PROCESS_PSS = 3,
    VX_MEMORY_ENVELOPE_PROCESS_PRIVATE_BYTES = 4,
    VX_MEMORY_ENVELOPE_PROCESS_MANAGED_HEAP_USED = 5,
    VX_MEMORY_ENVELOPE_PROCESS_EXTERNAL_BYTES = 6,
    VX_MEMORY_ENVELOPE_PROCESS_ARRAY_BUFFER_BYTES = 7,
    VX_MEMORY_ENVELOPE_DEVICE_PROCESS_USED = 8,
    VX_MEMORY_ENVELOPE_DEVICE_TOTAL_USED = 9,
    VX_MEMORY_ENVELOPE_DEVICE_TOTAL_CAPACITY = 10
};

typedef int32_t VxMemoryInventoryKind;
enum {
    VX_MEMORY_INVENTORY_UNSPECIFIED = 0,
    VX_MEMORY_INVENTORY_PARTIAL = 1,
    VX_MEMORY_INVENTORY_COMPLETE = 2
};

static inline int vx_graph_runtime_operator_name_is_current(
        const char* name) {
    static const char* const names[] = {
        "MatMul",
        "Linear",
        "QLinear",
        "BatchMatMul",
        "QBatchMatMul",
        "QGemm",
        "Gemm",
        "QMatMul",
        "MoERouter",
        "MoELinear",
        "SDPA",
        "QSDPA",
        "CrossSDPA",
        "CrossAttention",
        "LayerNorm",
        "QLayerNorm",
        "GroupNorm",
        "QGroupNorm",
        "RMSNorm",
        "BatchNorm2D",
        "Conv2D",
        "QConv2D",
        "Conv1D",
        "ConvTranspose2D",
        "MaxPool2D",
        "AveragePool2D",
        "GlobalAveragePool",
        "Resize",
        "Interpolate1D",
        "ResizeNearest2D",
        "UpsampleNearest2D",
        "ReLU",
        "LeakyReLU",
        "PReLU",
        "GELU",
        "QGELU",
        "SiLU",
        "QSiLU",
        "Sigmoid",
        "HardSwish",
        "HardSigmoid",
        "Tanh",
        "Sin",
        "Cos",
        "Clip",
        "Add",
        "QAdd",
        "Sub",
        "Mul",
        "Div",
        "Softmax",
        "LogSoftmax",
        "ReduceSum",
        "ReduceMean",
        "QMaskedMean",
        "ArgMax",
        "QArgMax",
        "Equal",
        "GreaterOrEqual",
        "Not",
        "Where",
        "Mask",
        "Reshape",
        "Flatten",
        "Squeeze",
        "Unsqueeze",
        "Transpose",
        "Concat",
        "Split",
        "Slice",
        "Pad",
        "Expand",
        "Gather",
        "GatherElements",
        "Identity",
        "Broadcast",
        "Concat2",
        "QuantizeLinear",
        "DequantizeLinear",
        "RequantizeLinear",
        "Cast",
        "Embedding",
        "QEmbedding",
        "RoPE",
        "SSMScan",
        "SelectiveScan",
        "NonMaxSuppression",
        "SpatialSoftargmaxY",
        "MeanHeight",
        "ProfileX",
        "ProfileY",
        "Dropout",
    };
    if (!name) return 0;
    for (size_t index = 0; index < sizeof(names) / sizeof(names[0]); index++) {
        const char* actual = name;
        const char* expected = names[index];
        while (*actual && *actual == *expected) {
            actual++;
            expected++;
        }
        if (*actual == *expected) return 1;
    }
    return 0;
}

#endif /* VOLVOXAI_ENUMS_H */
