/* DO NOT EDIT: generated by tools/generate_proto_enums.py. */
/* proto/volvoxai.proto SHA-256: 8b8294c1298a025e972b0cecb794f619c2e859944c49688f0f5c2dbc73fc7e90 */
#ifndef VOLVOXAI_FULL_ENUMS_H
#define VOLVOXAI_FULL_ENUMS_H

#include "volvoxai_enums.h"

enum {
    VX_STAGE_TRAINER_CREATE = 11,
    VX_STAGE_TRAINER_INPUT = 12,
    VX_STAGE_TRAINER_STEP = 13,
    VX_STAGE_TRAINER_COMMIT = 14,
    VX_STAGE_TRAINER_ROLLBACK = 15,
    VX_STAGE_TRAINER_EXPORT = 16,
    VX_STAGE_PTQ_CREATE = 17,
    VX_STAGE_PTQ_CALIBRATE = 18,
    VX_STAGE_PTQ_INSPECT = 19,
    VX_STAGE_PTQ_WRITE = 20,
    VX_STAGE_PTQ_CLOSE = 21
};

typedef int32_t VxOptimizerKind;
enum {
    VX_OPTIMIZER_ADAMW = 0,
    VX_OPTIMIZER_SGD = 1
};

typedef int32_t VxPTQMode;
enum {
    VX_PTQ_MODE_W8A8 = 0
};

typedef int32_t VxPTQScheme;
enum {
    VX_PTQ_SCHEME_SYMMETRIC = 0,
    VX_PTQ_SCHEME_ASYMMETRIC = 1
};

typedef int32_t VxPTQLayerKind;
enum {
    VX_PTQ_LAYER_QLINEAR = 0,
    VX_PTQ_LAYER_QCONV2D = 1
};

#endif /* VOLVOXAI_FULL_ENUMS_H */
