/* Generated by tools/generate_wasm_math.py from mathematical definitions. */
#ifndef VOLVOXAI_WASM_MATH_CONSTANTS_H
#define VOLVOXAI_WASM_MATH_CONSTANTS_H

#define VX_MATH_PI_OVER_TWO 0x1.921fb54442d18p+0
#define VX_MATH_PI_OVER_TWO_TAIL 0x1.1a62633145c07p-54
#define VX_MATH_PI_HIGH 0x1.921fb54000000p+0
#define VX_MATH_PI_MIDDLE 0x1.10b4611000000p-30
#define VX_MATH_PI_LOW 0x1.4c4c6628b80dcp-59
#define VX_MATH_TWO_OVER_PI 0x1.45f306dc9c883p-1
#define VX_MATH_LOG_TWO_HIGH 0x1.62e4200000000p-1
#define VX_MATH_LOG_TWO_LOW 0x1.fdf473de6af28p-22
#define VX_MATH_INV_LOG_TWO 0x1.71547652b82fep+0
#define VX_MATH_SQRT_HALF 0x1.6a09e667f3bcdp-1
#define VX_MATH_TWO_OVER_SQRT_PI 0x1.20dd750429b6dp+0

#define VX_MATH_RECIPROCAL_BITS 1280
static const uint32_t vx_math_reciprocal[] = {
    UINT32_C(0x9af4361d), UINT32_C(0xf0cfbc20), UINT32_C(0xfc7b6bab), UINT32_C(0x56033046),
    UINT32_C(0x1f8d5d08), UINT32_C(0x6bfb5fb1), UINT32_C(0x8a5292ea), UINT32_C(0x3d0739f7),
    UINT32_C(0xebe5f17b), UINT32_C(0x7527bac7), UINT32_C(0x9e5fea2d), UINT32_C(0x4f463f66),
    UINT32_C(0x27cb09b7), UINT32_C(0x6d367ecf), UINT32_C(0x5a0a6d1f), UINT32_C(0xef2f118b),
    UINT32_C(0xde05980f), UINT32_C(0x1ff897ff), UINT32_C(0xbdf9283b), UINT32_C(0x9c845f8b),
    UINT32_C(0x835339f4), UINT32_C(0x3991d639), UINT32_C(0xb45f7e41), UINT32_C(0xe99c7026),
    UINT32_C(0x2ebb4484), UINT32_C(0xe88235f5), UINT32_C(0xb129a73e), UINT32_C(0xfe1deb1c),
    UINT32_C(0x09d1921c), UINT32_C(0x06492eea), UINT32_C(0x424dd2e0), UINT32_C(0xb7246e3a),
    UINT32_C(0xdebbc561), UINT32_C(0xfe5163ab), UINT32_C(0x3c439041), UINT32_C(0xdb629599),
    UINT32_C(0xf534ddc0), UINT32_C(0xfc2757d1), UINT32_C(0x4e441529), UINT32_C(0xa2f9836e),
};

static const double vx_math_exp_series[] = {
    0x1.0000000000000p-1,
    0x1.5555555555555p-3,
    0x1.5555555555555p-5,
    0x1.1111111111111p-7,
    0x1.6c16c16c16c17p-10,
    0x1.a01a01a01a01ap-13,
    0x1.a01a01a01a01ap-16,
    0x1.71de3a556c734p-19,
    0x1.27e4fb7789f5cp-22,
    0x1.ae64567f544e4p-26,
    0x1.1eed8eff8d898p-29,
    0x1.6124613a86d09p-33,
    0x1.93974a8c07c9dp-37,
    0x1.ae7f3e733b81fp-41,
    0x1.ae7f3e733b81fp-45,
    0x1.952c77030ad4ap-49,
    0x1.6827863b97d97p-53,
    0x1.2f49b46814157p-57,
    0x1.e542ba4020225p-62,
};

static const double vx_math_log_series[] = {
    0x1.5555555555555p-2,
    0x1.999999999999ap-3,
    0x1.2492492492492p-3,
    0x1.c71c71c71c71cp-4,
    0x1.745d1745d1746p-4,
    0x1.3b13b13b13b14p-4,
    0x1.1111111111111p-4,
    0x1.e1e1e1e1e1e1ep-5,
    0x1.af286bca1af28p-5,
    0x1.8618618618618p-5,
    0x1.642c8590b2164p-5,
    0x1.47ae147ae147bp-5,
    0x1.2f684bda12f68p-5,
    0x1.1a7b9611a7b96p-5,
    0x1.0842108421084p-5,
    0x1.f07c1f07c1f08p-6,
    0x1.d41d41d41d41dp-6,
    0x1.bacf914c1bad0p-6,
    0x1.a41a41a41a41ap-6,
};

static const double vx_math_sin_series[] = {
    -0x1.5555555555555p-3,
    0x1.1111111111111p-7,
    -0x1.a01a01a01a01ap-13,
    0x1.71de3a556c734p-19,
    -0x1.ae64567f544e4p-26,
    0x1.6124613a86d09p-33,
    -0x1.ae7f3e733b81fp-41,
    0x1.952c77030ad4ap-49,
    -0x1.2f49b46814157p-57,
};

static const double vx_math_cos_series[] = {
    -0x1.0000000000000p-1,
    0x1.5555555555555p-5,
    -0x1.6c16c16c16c17p-10,
    0x1.a01a01a01a01ap-16,
    -0x1.27e4fb7789f5cp-22,
    0x1.1eed8eff8d898p-29,
    -0x1.93974a8c07c9dp-37,
    0x1.ae7f3e733b81fp-45,
    -0x1.6827863b97d97p-53,
    0x1.e542ba4020225p-62,
};

#endif
