#!/usr/bin/env python3
"""Deterministically embed a NUL-terminated CUDA PTX module in C sources."""

from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path


SYMBOL = "volvoxai_cuda_ptx"
SIZE_SYMBOL = "volvoxai_cuda_ptx_size"
BYTES_PER_LINE = 12
_C_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def input_hash(ptx: bytes) -> str:
    """Return the stable digest recorded in both generated files."""

    return hashlib.sha256(ptx).hexdigest()


def validate_ptx(ptx: bytes) -> None:
    if not ptx:
        raise ValueError("CUDA PTX input is empty")
    if b"\x00" in ptx:
        raise ValueError("CUDA PTX input already contains a NUL byte")


def validate_symbol(symbol: str) -> None:
    if not _C_IDENTIFIER.fullmatch(symbol):
        raise ValueError(f"invalid C symbol: {symbol!r}")


def size_symbol(symbol: str) -> str:
    validate_symbol(symbol)
    return SIZE_SYMBOL if symbol == SYMBOL else f"{symbol}_size"


def header_guard(symbol: str) -> str:
    validate_symbol(symbol)
    if symbol == SYMBOL:
        return "VOLVOXAI_EMBEDDED_CUDA_PTX_H"
    return f"VOLVOXAI_EMBEDDED_{symbol.upper()}_H"


def render_header(digest: str, symbol: str = SYMBOL) -> str:
    guard = header_guard(symbol)
    payload_size_symbol = size_symbol(symbol)
    return f"""/* DO NOT EDIT: generated by tools/embed_cuda_ptx.py.
 * Input SHA-256: {digest}
 */
#ifndef {guard}
#define {guard}

#include <stddef.h>

extern const unsigned char {symbol}[];
/* PTX payload bytes, excluding the trailing NUL stored in the array. */
extern const size_t {payload_size_symbol};

#endif
"""


def render_source(
    ptx: bytes, digest: str, header_name: str, symbol: str = SYMBOL
) -> str:
    validate_ptx(ptx)
    validate_symbol(symbol)
    payload_size_symbol = size_symbol(symbol)
    encoded = ptx + b"\x00"
    lines = []
    for offset in range(0, len(encoded), BYTES_PER_LINE):
        chunk = encoded[offset : offset + BYTES_PER_LINE]
        lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    body = "\n".join(lines)
    return f"""/* DO NOT EDIT: generated by tools/embed_cuda_ptx.py.
 * Input SHA-256: {digest}
 */
#include \"{header_name}\"

const unsigned char {symbol}[] = {{
{body}
}};

const size_t {payload_size_symbol} = sizeof({symbol}) - 1u;
"""


def write_embedded_ptx(
    ptx_path: Path, output_c: Path, output_h: Path, symbol: str = SYMBOL
) -> None:
    ptx = ptx_path.read_bytes()
    validate_ptx(ptx)
    validate_symbol(symbol)
    digest = input_hash(ptx)
    header = render_header(digest, symbol)
    source = render_source(ptx, digest, output_h.name, symbol)

    output_c.parent.mkdir(parents=True, exist_ok=True)
    output_h.parent.mkdir(parents=True, exist_ok=True)
    output_h.write_text(header, encoding="utf-8", newline="\n")
    output_c.write_text(source, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=Path, help="input CUDA PTX file")
    parser.add_argument("--output-c", required=True, type=Path,
                        help="generated C byte-array source")
    parser.add_argument("--output-h", required=True, type=Path,
                        help="generated C declaration header")
    parser.add_argument("--symbol", default=SYMBOL,
                        help="C byte-array symbol (default: %(default)s)")
    args = parser.parse_args()
    write_embedded_ptx(args.input, args.output_c, args.output_h, args.symbol)


if __name__ == "__main__":
    main()
