#!/usr/bin/env python3
"""Generate the dependency-free WebAssembly SIMD128 capability probe."""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "tools/generated/wasmSimdProbe.ts"


def unsigned_leb128(value: int) -> bytes:
    if value < 0:
        raise ValueError("unsigned LEB128 values must be non-negative")
    encoded = bytearray()
    while True:
        byte = value & 0x7F
        value >>= 7
        encoded.append(byte | (0x80 if value else 0))
        if not value:
            return bytes(encoded)


def section(identifier: int, payload: bytes) -> bytes:
    return bytes((identifier,)) + unsigned_leb128(len(payload)) + payload


def probe_module() -> bytes:
    # () -> v128, with a single v128.const body. Validation therefore proves
    # support for the SIMD value type and SIMD instruction prefix without
    # instantiating, importing, or executing a module.
    function_type = bytes((1, 0x60, 0, 1, 0x7B))
    function_declaration = bytes((1, 0))
    body = bytes((0, 0xFD)) + unsigned_leb128(12) + bytes(16) + bytes((0x0B,))
    code = bytes((1,)) + unsigned_leb128(len(body)) + body
    return (
        bytes((0, 0x61, 0x73, 0x6D, 1, 0, 0, 0))
        + section(1, function_type)
        + section(3, function_declaration)
        + section(10, code)
    )


def render_typescript(module: bytes) -> bytes:
    rows = []
    for offset in range(0, len(module), 12):
        values = ", ".join(f"0x{value:02x}" for value in module[offset:offset + 12])
        rows.append(f"  {values},")
    return (
        "// DO NOT EDIT: generated by tools/generate_wasm_simd_probe.py.\n"
        "// Minimal () -> v128 module containing v128.const.\n"
        "export const WASM_SIMD128_PROBE_BYTES = new Uint8Array([\n"
        + "\n".join(rows)
        + "\n]);\n"
    ).encode()


def write_atomic(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    temporary.write_bytes(data)
    os.replace(temporary, path)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    output = args.output.resolve()
    expected = render_typescript(probe_module())
    if args.check:
        if not output.is_file() or output.read_bytes() != expected:
            print(f"stale generated WASM SIMD probe: {output}", file=sys.stderr)
            print("run python3 tools/generate_wasm_simd_probe.py", file=sys.stderr)
            return 1
        print(f"Verified generated WASM SIMD128 probe ({len(probe_module())} bytes)")
        return 0
    write_atomic(output, expected)
    print(f"Generated {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
