#!/usr/bin/env python3
"""Project pinned Unicode letter/number categories for C pretokenization."""
import argparse
import hashlib
import json
from pathlib import Path
from urllib.error import URLError
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
SOURCE_URL = 'https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt'
LICENSE = ROOT / 'native/third_party/unicode/LICENSE.txt'
TARGET = ROOT / 'native/src/generated/tokenizer_unicode.h'
LICENSE_TARGET = ROOT / 'native/src/generated/tokenizer_unicode_license.inc'
SHA256 = '2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c'


def render():
    try:
        with urlopen(SOURCE_URL, timeout=30) as response:
            raw = response.read()
    except (OSError, URLError) as error:
        raise SystemExit(f'could not download pinned UnicodeData from {SOURCE_URL}: {error}') from error
    if hashlib.sha256(raw).hexdigest() != SHA256:
        raise SystemExit('pinned UnicodeData source digest mismatch')
    ranges = []
    first = None
    for line in raw.decode('utf8').splitlines():
        fields = line.split(';')
        code = int(fields[0], 16)
        kind = {'L': 1, 'N': 2}.get(fields[2][0], 0)
        if fields[1].endswith(', First>'):
            first = code
            continue
        low = first if fields[1].endswith(', Last>') else code
        first = None
        if not kind:
            continue
        if ranges and ranges[-1][1] + 1 == low and ranges[-1][2] == kind:
            ranges[-1] = (ranges[-1][0], code, kind)
        else:
            ranges.append((low, code, kind))
    body = '\n'.join(f'    {{0x{low:x}u, 0x{high:x}u, {kind}u}},' for low, high, kind in ranges)
    return f'''/* Generated by tools/generate_tokenizer_unicode.py. Do not edit.
 * Unicode 17.0.0, https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt
 * Source SHA-256: {SHA256}
 * Unicode license: native/third_party/unicode/LICENSE.txt */
#ifndef VOLVOXAI_TOKENIZER_UNICODE_H
#define VOLVOXAI_TOKENIZER_UNICODE_H
#include <stdint.h>
static const struct {{ uint32_t low, high, kind; }} vx_unicode_categories[] = {{
{body}
}};
#endif
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    notice = LICENSE.read_text()
    assembly = '.section .custom_section.license.unicode,"",@\n'
    for line in notice.splitlines(keepends=True):
        assembly += '.ascii ' + json.dumps(line, ensure_ascii=False) + '\n'
    license_code = ('/* Generated Unicode data license. Do not edit. */\n'
                    '#if defined(__wasm__)\n__asm__(' + json.dumps(assembly) + ');\n'
                    '#else\nstatic const volatile char vx_unicode_license[] =\n' +
                    json.dumps(notice, ensure_ascii=False) + ';\n#endif\n')
    for target, result in [(TARGET, render()), (LICENSE_TARGET, license_code)]:
        if args.check:
            if not target.exists() or target.read_text() != result:
                raise SystemExit('stale tokenizer Unicode projection; run tools/generate_tokenizer_unicode.py')
        else:
            target.write_text(result)


if __name__ == '__main__':
    main()
