#!/usr/bin/env python3
"""Generate dependency-free projections of the internal operator vocabulary."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OPERATOR_PREFIX = "OPERATOR_KIND_"

_OPERATOR_GRAPH_TOKEN_CASE = {
    "Q": "Q",
    "MATMUL": "MatMul",
    "SDPA": "SDPA",
    "RMS": "RMS",
    "SSM": "SSM",
    "MOE": "MoE",
    "ROPE": "RoPE",
    "RELU": "ReLU",
    "GELU": "GELU",
    "SILU": "SiLU",
    "PRELU": "PReLU",
    "1D": "1D",
    "2D": "2D",
}


def strip_comments(source: str) -> str:
    source = re.sub(r"/\*.*?\*/", "", source, flags=re.DOTALL)
    return re.sub(r"//[^\n]*", "", source)


def parse_operator_vocabulary(
    source: str,
) -> dict[str, tuple[tuple[str, int], ...]]:
    """Parse the internal operator and fixed-port vocabulary."""
    clean = strip_comments(source)
    if re.search(r"\bpackage\s+volvoxai\.operator_vocabulary\s*;", clean) is None:
        raise ValueError("operator vocabulary has the wrong protobuf package")
    specs = {"OperatorKind": OPERATOR_PREFIX, "PortKind": "PORT_KIND_"}
    declared = set(re.findall(r"\benum\s+(\w+)\s*\{", clean))
    if declared != set(specs):
        raise ValueError(f"unexpected operator vocabulary enums: {sorted(declared)}")
    enums = {}
    for enum_name, prefix in specs.items():
        match = re.search(rf"\benum\s+{enum_name}\s*\{{(.*?)\}}", clean, re.DOTALL)
        assert match is not None
        entries = []
        for statement in match[1].split(";"):
            statement = statement.strip()
            if not statement:
                continue
            entry = re.fullmatch(r"([A-Z][A-Z0-9_]*)\s*=\s*(-?[0-9]+)", statement)
            if not entry or not entry[1].startswith(prefix):
                raise ValueError(f"unsupported {enum_name} declaration: {statement!r}")
            entries.append((entry[1], int(entry[2])))
        if not entries or entries[0] != (prefix + "UNSPECIFIED", 0):
            raise ValueError(f"{enum_name} must start with its zero-valued default")
        if len({n for n, _ in entries}) != len(entries) or len({v for _, v in entries}) != len(entries):
            raise ValueError(f"{enum_name} has duplicate names or numbers")
        enums[enum_name] = tuple(entries)
    return enums


def port_name(proto_name: str) -> str:
    suffix = proto_name.removeprefix("PORT_KIND_")
    return suffix.removeprefix("SSM_") if suffix.startswith("SSM_") else suffix.lower()


def operator_graph_name(proto_name: str) -> str:
    """Return the sole volvox-graph/v1 spelling for one enum value."""

    suffix = proto_name.removeprefix(OPERATOR_PREFIX)
    return "".join(
        _OPERATOR_GRAPH_TOKEN_CASE.get(token, token.lower().capitalize())
        for token in suffix.split("_")
    )


def operator_graph_entries(
    enums: dict[str, tuple[tuple[str, int], ...]],
) -> tuple[tuple[str, int, str], ...]:
    result = tuple(
        (name, value, operator_graph_name(name))
        for name, value in enums["OperatorKind"]
        if value != 0
    )
    graph_names = [graph_name for _, _, graph_name in result]
    if len(graph_names) != len(set(graph_names)):
        raise ValueError("OperatorKind graph spellings must be unique")
    return result


def camel_case(suffix: str) -> str:
    parts = suffix.lower().split("_")
    return parts[0].capitalize() + "".join(part.capitalize() for part in parts[1:])


def generated_banner(vocabulary_hash: str, marker: str) -> str:
    return (
        f"{marker} DO NOT EDIT: generated by tools/generate_operator_vocabulary.py.\n"
        f"{marker} proto/operator_vocabulary.proto SHA-256: {vocabulary_hash}\n"
    )


def render_c(
    enums: dict[str, tuple[tuple[str, int], ...]], vocabulary_hash: str
) -> bytes:
    entries = enums["OperatorKind"]
    constants = [
        f"    VX_OP_{name.removeprefix(OPERATOR_PREFIX)} = {value}"
        + ("," if index + 1 < len(entries) else "")
        for index, (name, value) in enumerate(entries)
    ]
    body = (
        "typedef int32_t VxOperatorKind;\n"
        "enum {\n"
        + "\n".join(constants)
        + "\n};\n\n"
        "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"
        "/* Convert only at graph/API and diagnostic boundaries. Unknown names\n"
        " * map to UNSPECIFIED; unknown kinds (including zero) have no name. */\n"
        "VxOperatorKind vx_operator_kind_from_name(const char* name);\n"
        "VxOperatorKind vx_operator_kind_from_bytes(const void* data, size_t length);\n"
        "const char* vx_operator_kind_name(VxOperatorKind kind);\n\n"
        "#ifdef __cplusplus\n}\n#endif\n"
    )
    ports = enums["PortKind"]
    body = "typedef int32_t VxPortKind;\nenum {\n" + "\n".join(
        f"    VX_PORT_{name.removeprefix('PORT_KIND_')} = {value},"
        for name, value in ports
    ) + "\n};\n\n" + body
    body = body.replace('#ifdef __cplusplus\n}\n#endif',
        'VxPortKind vx_port_kind_from_name(const char* name);\n'
        'VxPortKind vx_port_kind_from_bytes(const void* data, size_t length);\n'
        'const char* vx_port_kind_name(VxPortKind kind);\n\n'
        '#ifdef __cplusplus\n}\n#endif')
    content = (
        generated_banner(vocabulary_hash, "/*").replace("\n", " */\n")
        + "#ifndef VOLVOXAI_INTERNAL_OPERATOR_VOCABULARY_H\n"
        "#define VOLVOXAI_INTERNAL_OPERATOR_VOCABULARY_H\n\n"
        "#include <stddef.h>\n#include <stdint.h>\n\n"
        + body
        + "\n#endif /* VOLVOXAI_INTERNAL_OPERATOR_VOCABULARY_H */\n"
    )
    return content.encode()


def render_name_lookup(c_type: str, prefix: str, stem: str, entries: list[tuple[str, str]]) -> str:
    """Length-aware boundary decoding and diagnostic naming share one table."""
    rows = [f"    {{{constant}, {json.dumps(name)}}}," for constant, name in sorted(entries, key=lambda item: item[1])]
    return f"""
static const struct {{ {c_type} kind; const char* name; }} vx_{stem}_names[] = {{
{chr(10).join(rows)}
}};

{c_type} vx_{stem}_kind_from_bytes(const void* data, size_t length) {{
    size_t begin = 0, end = sizeof(vx_{stem}_names) / sizeof(vx_{stem}_names[0]);
    if (!data) return {prefix}UNSPECIFIED;
    while (begin < end) {{
        size_t middle = begin + (end - begin) / 2;
        const char* name = vx_{stem}_names[middle].name;
        size_t name_length = strlen(name);
        size_t common = length < name_length ? length : name_length;
        int order = memcmp(data, name, common);
        if (!order) order = (length > name_length) - (length < name_length);
        if (!order) return vx_{stem}_names[middle].kind;
        if (order < 0) end = middle;
        else begin = middle + 1;
    }}
    return {prefix}UNSPECIFIED;
}}

{c_type} vx_{stem}_kind_from_name(const char* name) {{
    return name ? vx_{stem}_kind_from_bytes(name, strlen(name)) : {prefix}UNSPECIFIED;
}}

const char* vx_{stem}_kind_name({c_type} kind) {{
    for (size_t i = 0; i < sizeof(vx_{stem}_names) / sizeof(vx_{stem}_names[0]); i++)
        if (vx_{stem}_names[i].kind == kind) return vx_{stem}_names[i].name;
    return NULL;
}}
"""


def render_c_source(
    enums: dict[str, tuple[tuple[str, int], ...]], vocabulary_hash: str
) -> bytes:
    content = generated_banner(vocabulary_hash, "/*").replace("\n", " */\n")
    content += '#include "operator_vocabulary.h"\n#include <string.h>\n'
    content += render_name_lookup("VxOperatorKind", "VX_OP_", "operator", [
        ("VX_OP_" + name.removeprefix(OPERATOR_PREFIX), graph_name)
        for name, _, graph_name in operator_graph_entries(enums)
    ])
    content += render_name_lookup("VxPortKind", "VX_PORT_", "port", [
        ("VX_PORT_" + name.removeprefix("PORT_KIND_"), port_name(name))
        for name, value in enums["PortKind"] if value
    ])
    return content.encode()


def render_typescript(
    enums: dict[str, tuple[tuple[str, int], ...]], vocabulary_hash: str
) -> bytes:
    enum_lines = [
        f"  {camel_case(name.removeprefix(OPERATOR_PREFIX))} = {value},"
        for name, value in enums["OperatorKind"]
    ]
    graph_names = [name for _, _, name in operator_graph_entries(enums)]
    content = (
        generated_banner(vocabulary_hash, "//")
        + "export enum OperatorKind {\n"
        + "\n".join(enum_lines)
        + "\n}\n\n"
        "export const runtimeOperatorNames = Object.freeze(["
        + ", ".join(repr(name) for name in graph_names)
        + "] as const);\n"
        "export type RuntimeOperatorName = (typeof runtimeOperatorNames)[number];\n"
    )
    content += "\nexport enum PortKind {\n" + "\n".join(
        f"  {camel_case(name.removeprefix('PORT_KIND_'))} = {value},"
        for name, value in enums["PortKind"]
    ) + "\n}\n"
    return content.encode()


def render_python(
    enums: dict[str, tuple[tuple[str, int], ...]], vocabulary_hash: str
) -> bytes:
    enum_lines = [
        f"    {name.removeprefix(OPERATOR_PREFIX)} = {value}"
        for name, value in enums["OperatorKind"]
    ]
    graph_entries = operator_graph_entries(enums)
    name_lines = [
        f"    OperatorKind.{name.removeprefix(OPERATOR_PREFIX)}: {graph_name!r},"
        for name, _, graph_name in graph_entries
    ]
    runtime_lines = [f"    {graph_name!r}," for _, _, graph_name in graph_entries]
    content = (
        generated_banner(vocabulary_hash, "#")
        + "\nfrom enum import IntEnum\n\n\n"
        "class OperatorKind(IntEnum):\n"
        + "\n".join(enum_lines)
        + "\n\n\nOPERATOR_GRAPH_NAMES = {\n"
        + "\n".join(name_lines)
        + "\n}\n\nRUNTIME_OPERATOR_NAMES = (\n"
        + "\n".join(runtime_lines)
        + "\n)\n"
    )
    content += "\n\nclass PortKind(IntEnum):\n" + "\n".join(
        f"    {name.removeprefix('PORT_KIND_')} = {value}"
        for name, value in enums["PortKind"]
    ) + "\n\nPORT_NAMES = {\n" + "\n".join(
        f"    PortKind.{name.removeprefix('PORT_KIND_')}: {port_name(name)!r},"
        for name, value in enums["PortKind"] if value
    ) + "\n}\n"
    return content.encode()


def render_javascript(
    enums: dict[str, tuple[tuple[str, int], ...]], vocabulary_hash: str
) -> bytes:
    graph_entries = operator_graph_entries(enums)
    graph_names = [name for _, _, name in graph_entries]
    c_constants = {
        graph_name: "VX_OP_" + name.removeprefix(OPERATOR_PREFIX)
        for name, _, graph_name in graph_entries
    }
    content = (
        generated_banner(vocabulary_hash, "//")
        + "\nexport const runtimeOperatorNames = Object.freeze("
        + json.dumps(graph_names, separators=(",", ":"))
        + ");\n"
        + "\nexport const runtimeOperatorCConstants = Object.freeze("
        + json.dumps(c_constants, indent=2)
        + ");\n"
    )
    content += "\nexport const runtimePortCConstants = Object.freeze(" + json.dumps({
        port_name(name): "VX_PORT_" + name.removeprefix("PORT_KIND_")
        for name, value in enums["PortKind"] if value
    }, indent=2) + ");\n"
    return content.encode()


def write_atomic(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    temporary.write_bytes(data)
    os.replace(temporary, path)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--proto", type=Path, default=ROOT / "proto/operator_vocabulary.proto"
    )
    parser.add_argument(
        "--native-out",
        type=Path,
        default=ROOT / "native/src/generated/operator_vocabulary.h",
    )
    parser.add_argument(
        "--native-source-out",
        type=Path,
        default=ROOT / "native/src/generated/operator_vocabulary.c",
    )
    parser.add_argument(
        "--typescript-out",
        type=Path,
        default=ROOT / "tools/generated/operatorVocabulary.ts",
    )
    parser.add_argument(
        "--python-out",
        type=Path,
        default=ROOT / "tools/exporter/generated/operator_vocabulary.py",
    )
    parser.add_argument(
        "--javascript-out",
        type=Path,
        default=ROOT / "tools/generated/volvoxaiGraphOperators.mjs",
    )
    args = parser.parse_args()

    try:
        source_bytes = args.proto.resolve().read_bytes()
        enums = parse_operator_vocabulary(source_bytes.decode("utf-8"))
        vocabulary_hash = hashlib.sha256(source_bytes).hexdigest()
        outputs = {
            args.native_out.resolve(): render_c(enums, vocabulary_hash),
            args.native_source_out.resolve(): render_c_source(enums, vocabulary_hash),
            args.typescript_out.resolve(): render_typescript(enums, vocabulary_hash),
            args.python_out.resolve(): render_python(enums, vocabulary_hash),
            args.javascript_out.resolve(): render_javascript(enums, vocabulary_hash),
        }
    except (OSError, UnicodeDecodeError, ValueError) as error:
        print(f"operator vocabulary generation failed: {error}", file=sys.stderr)
        return 1

    stale = [
        path
        for path, data in outputs.items()
        if not path.is_file() or path.read_bytes() != data
    ]
    if args.check:
        if stale:
            for path in stale:
                print(f"stale generated operator vocabulary: {path}", file=sys.stderr)
            print("run make operator_vocabulary_codegen", file=sys.stderr)
            return 1
        print(f"Verified {len(outputs)} generated operator vocabulary files")
        return 0

    for path, data in outputs.items():
        write_atomic(path, data)
        print(f"Generated {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
