#!/usr/bin/env python3
"""Derive WASM scalar constants from mathematical definitions.

No coefficient tables or implementation sources are imported. Pi is evaluated
as 16 atan(1/5) - 4 atan(1/239), using the alternating arctangent series.
Taylor coefficients are exact rational factorials. Two working precisions must
produce identical binary constants before they can be written or checked.
"""
import argparse
from decimal import Decimal, localcontext
from math import factorial
from pathlib import Path
import struct

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "native/src/runtime/wasm_math_constants.h"


def arctangent(value):
    total = term = value
    squared = -(value * value)
    denominator = 3
    while True:
        term *= squared
        updated = total + term / denominator
        if updated == total:
            return total
        total = updated
        denominator += 2


def split(value, clear_bits):
    raw = struct.unpack(">Q", struct.pack(">d", float(value)))[0]
    high = struct.unpack(">d", struct.pack(">Q", raw & ~((1 << clear_bits) - 1)))[0]
    return high, value - Decimal.from_float(high)


def generate(precision):
    with localcontext() as context:
        context.prec = precision
        pi = 16 * arctangent(Decimal(1) / 5) - 4 * arctangent(Decimal(1) / 239)
        half_pi = pi / 2
        pi_high, remaining = split(half_pi, 24)
        pi_middle, pi_low = split(remaining, 24)
        log_high, log_low = split(Decimal(2).ln(), 32)
        constants = {
            "VX_MATH_PI_OVER_TWO": half_pi,
            "VX_MATH_PI_OVER_TWO_TAIL": half_pi - Decimal.from_float(float(half_pi)),
            "VX_MATH_PI_HIGH": pi_high,
            "VX_MATH_PI_MIDDLE": pi_middle,
            "VX_MATH_PI_LOW": pi_low,
            "VX_MATH_TWO_OVER_PI": 2 / pi,
            "VX_MATH_LOG_TWO_HIGH": log_high,
            "VX_MATH_LOG_TWO_LOW": log_low,
            "VX_MATH_INV_LOG_TWO": 1 / Decimal(2).ln(),
            "VX_MATH_SQRT_HALF": (Decimal(1) / 2).sqrt(),
            "VX_MATH_TWO_OVER_SQRT_PI": 2 / pi.sqrt(),
        }
        lines = ["/* Generated by tools/generate_wasm_math.py from mathematical definitions. */",
                 "#ifndef VOLVOXAI_WASM_MATH_CONSTANTS_H",
                 "#define VOLVOXAI_WASM_MATH_CONSTANTS_H", ""]
        for name, value in constants.items():
            lines.append(f"#define {name} {float(value).hex()}")
        reciprocal_bits = 1280
        reciprocal = int((2 / pi) * (1 << reciprocal_bits))
        lines += ["", f"#define VX_MATH_RECIPROCAL_BITS {reciprocal_bits}",
                  "static const uint32_t vx_math_reciprocal[] = {"]
        words = [(reciprocal >> offset) & 0xffffffff for offset in range(0, reciprocal_bits, 32)]
        for offset in range(0, len(words), 4):
            lines.append("    " + ", ".join(f"UINT32_C(0x{word:08x})" for word in words[offset:offset + 4]) + ",")
        lines += ["};", ""]
        series = {
            "exp": [Decimal(1) / factorial(k) for k in range(2, 21)],
            "log": [Decimal(1) / k for k in range(3, 40, 2)],
            "sin": [Decimal((-1) ** k) / factorial(2 * k + 1) for k in range(1, 10)],
            "cos": [Decimal((-1) ** k) / factorial(2 * k) for k in range(1, 11)],
        }
        for name, coefficients in series.items():
            lines.append(f"static const double vx_math_{name}_series[] = {{")
            lines.extend(f"    {float(coefficient).hex()}," for coefficient in coefficients)
            lines += ["};", ""]
        return "\n".join(lines + ["#endif", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = generate(500)
    if source != generate(600):
        raise SystemExit("constant generation did not converge")
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != source:
            raise SystemExit("stale WASM math constants; run tools/generate_wasm_math.py")
    else:
        OUTPUT.write_text(source)


if __name__ == "__main__":
    main()
