/* DO NOT EDIT: generated by tools/generate_wasm_internal_abi.mjs. */
#ifndef VOLVOXAI_BACKENDS_GPU_BRIDGE_H
#define VOLVOXAI_BACKENDS_GPU_BRIDGE_H
#include <stdint.h>
#define VX_GPU_BRIDGE_ABI_VERSION 6u
#define VX_GPU_BRIDGE_ABI_HASH "641d197d75a214dfa41109bb55ab95d3df1240dcc1496c8c40680c2071dd618a"
#define VX_GPU_PENDING (-2)
#define VX_GPU_ERROR (-1)
#define VX_GPU_DEVICE_LOST (-3)
#define VX_GPU_OK (0)
#define VX_GPU_NO_UNIFORM (255)
typedef struct {
    uint32_t variant_count;
    uint32_t binding_count;
    uint32_t params_bytes;
    uint32_t node_index;
    uint32_t params_slot;
} VxGpuDispatch;
typedef struct {
    uint32_t shader_id;
    uint32_t workgroup[3];
} VxGpuVariant;
typedef struct {
    uint32_t slot;
    uint32_t host_ptr;
    uint32_t offset;
    uint32_t bytes;
    uint32_t writes;
} VxGpuBinding;
typedef struct {
    uint32_t maxBufferSize;
    uint32_t maxStorageBufferBindingSize;
    uint32_t maxUniformBufferBindingSize;
    uint32_t maxStorageBuffersPerShaderStage;
    uint32_t maxUniformBuffersPerShaderStage;
    uint32_t maxBindingsPerBindGroup;
    uint32_t maxBindGroups;
    uint32_t minStorageBufferOffsetAlignment;
    uint32_t maxComputeWorkgroupStorageSize;
    uint32_t maxComputeInvocationsPerWorkgroup;
    uint32_t maxComputeWorkgroupSizeX;
    uint32_t maxComputeWorkgroupSizeY;
    uint32_t maxComputeWorkgroupSizeZ;
    uint32_t maxComputeWorkgroupsPerDimension;
} VxGpuLimits;
#if defined(__wasm__)
#define VX_GPU_IMPORT __attribute__((import_module("gpu")))
#else
#define VX_GPU_IMPORT
#endif
VX_GPU_IMPORT int vx_gpu_available(uint32_t abi_hash, uint32_t catalog_hash);
VX_GPU_IMPORT int vx_gpu_limits(uint32_t destination, uint32_t bytes);
VX_GPU_IMPORT int vx_gpu_ensure(uint32_t host_ptr, uint32_t bytes, int is_weight);
VX_GPU_IMPORT void vx_gpu_release(uint32_t host_ptr);
VX_GPU_IMPORT void vx_gpu_invalidate(uint32_t host_ptr);
VX_GPU_IMPORT void vx_gpu_begin(void);
VX_GPU_IMPORT int vx_gpu_encode(uint32_t dispatch);
VX_GPU_IMPORT int vx_gpu_end(void);
VX_GPU_IMPORT int vx_gpu_snapshot(uint32_t host_ptr, uint32_t offset, uint32_t bytes);
VX_GPU_IMPORT int vx_gpu_readback(uint32_t ticket, uint32_t destination, uint32_t bytes);
VX_GPU_IMPORT void vx_gpu_readback_release(uint32_t ticket);
#endif
