/* DO NOT EDIT: generated by tools/generate_shader_catalog.mjs. */
/* Shader source SHA-256: 553dc4efc879ea9e3cec4c970bf4757563b94a0505db893a98f67a511bb38e1d */

/*
 * Shader identity for the engine.
 *
 * The engine names a shader when it plans a node; it never holds WGSL text.
 * These ids are what `VxGpuVariant.shader_id` carries across the device
 * bridge, and the host resolves them through the matching generated table.
 */

#ifndef VOLVOXAI_BACKENDS_SHADER_CATALOG_GENERATED_H
#define VOLVOXAI_BACKENDS_SHADER_CATALOG_GENERATED_H

#include <stdint.h>
#define VX_SHADER_CATALOG_HASH "a04d285c5c9351909a6af367e8004aa556e05c8d6738fc71e50212deaca9cd8e"

#define VX_SHADER_COUNT UINT32_C(133)

/*
 * What a shader declares about how it must be called.
 *
 * All of it is read from the WGSL: which slot each buffer occupies, which of
 * them the dispatch writes, where the uniform block sits and how large it is,
 * and the workgroup size. The engine builds its descriptor from this rather
 * than restating it, because a restatement can disagree -- and the way it
 * disagrees is a dispatch that runs, succeeds, and writes the wrong bytes.
 *
 * A storage_count above VX_SHADER_MAX_PLANNED_BINDINGS means this engine
 * cannot describe the shader; a params_slot of 255 means it binds no uniform.
 */
#define VX_SHADER_MAX_PLANNED_BINDINGS 16

typedef struct {
    uint8_t slots[VX_SHADER_MAX_PLANNED_BINDINGS];
    uint8_t storage_count;
    uint16_t writes_mask;
    uint8_t params_slot;
    uint16_t params_bytes;
    uint16_t workgroup[3];
    uint32_t workgroup_bytes;
} VxShaderInterface;

/* Copied into opt-in traces only; IDs still use the canonical catalogue. */
static const struct { const char* name; const char* entry; }
vx_shader_programs[VX_SHADER_COUNT] = {
    { "add", "main" },
    { "add3Relu", "main" },
    { "addRelu", "main" },
    { "argMaxF32", "main" },
    { "argMaxF32I32Native", "main" },
    { "argMaxI32", "main" },
    { "argMaxI8", "main" },
    { "averagePool2D", "main" },
    { "batchMatMul", "main" },
    { "batchNorm2D", "main" },
    { "binaryBroadcast", "main" },
    { "broadcastAdd", "main" },
    { "broadcastAddReLU", "main" },
    { "broadcastAddReLU6", "main" },
    { "broadcastBinaryNative", "main" },
    { "broadcastDiv", "main" },
    { "broadcastMul", "main" },
    { "broadcastSub", "main" },
    { "cast", "main" },
    { "clip", "main" },
    { "clipTyped", "main" },
    { "compareI32", "main" },
    { "concat2", "main" },
    { "concatCopy", "main" },
    { "concatCopy32", "main" },
    { "concatCopy32Native", "main" },
    { "concatCopyTyped", "main" },
    { "concatSigmoidCopy", "main" },
    { "conv1D", "main" },
    { "conv2D", "main" },
    { "conv2DDepthwise4", "main" },
    { "conv2DDepthwise8", "main" },
    { "conv2DPointwise16", "main" },
    { "conv2DPointwise16Tile", "main" },
    { "conv2DPointwise8", "main" },
    { "conv2DPointwise8Vec2", "main" },
    { "conv2DPointwise8Vec4", "main" },
    { "conv2DRegularC3Out16", "main" },
    { "conv2DRegularOut16", "main" },
    { "convTranspose2D", "main" },
    { "copy", "main" },
    { "copy32", "main" },
    { "copyTyped", "main" },
    { "crossAttention", "main" },
    { "crossAttentionF32", "main" },
    { "crossSDPA", "main" },
    { "decodeKeepMask", "main" },
    { "denseF32", "main" },
    { "dequantizeLinear", "main" },
    { "dequantizeLinearTyped", "main" },
    { "div", "main" },
    { "elementwise", "main" },
    { "embedding", "main" },
    { "expand", "main" },
    { "expandTyped", "main" },
    { "gELU", "main" },
    { "gather", "main" },
    { "gatherElements", "main" },
    { "gatherInt32", "main" },
    { "generalTranspose", "main" },
    { "globalAveragePool", "main" },
    { "groupNorm", "main" },
    { "hardSigmoid", "main" },
    { "hardSwish", "main" },
    { "incrementalRowByteCopy", "main" },
    { "interp1D", "main" },
    { "layerNorm", "main" },
    { "leakyReLU", "main" },
    { "linearF32", "main" },
    { "linearF32RowMajor", "main" },
    { "linearF32RowMajorTiled", "main" },
    { "linearF32Tiled", "main" },
    { "linearInt8", "main" },
    { "linearInt8Tiled", "main" },
    { "logSoftmax", "main" },
    { "loraApply", "main" },
    { "maxPool2D", "main" },
    { "maxPool2DTyped", "main" },
    { "meanHeight", "main" },
    { "moeLinear", "main" },
    { "moeRouter", "main" },
    { "mul", "main" },
    { "nonMaxSuppression", "main" },
    { "notI32", "main" },
    { "pReLU", "main" },
    { "pad", "main" },
    { "profileX", "main" },
    { "profileY", "main" },
    { "qAdd", "main" },
    { "qArgMaxInt8", "main" },
    { "qBatchMatMul", "main" },
    { "qBatchMatMulDot", "main" },
    { "qConv2DInt8", "main" },
    { "qConv2DInt8DotTiled", "main" },
    { "qConv2DInt8Tiled", "main" },
    { "qEmbeddingInt8", "main" },
    { "qGELUInt8", "main" },
    { "qGroupNormApply", "main" },
    { "qGroupNormStats", "main" },
    { "qLayerNormApply", "main" },
    { "qLayerNormStats", "main" },
    { "qLinearInt8", "main" },
    { "qLinearInt8Dot", "main" },
    { "qLinearInt8DotTiled", "main" },
    { "qLinearInt8Tiled", "main" },
    { "qMaskedMeanInt8", "main" },
    { "qSDPAInt8", "main" },
    { "qSiLUInt8", "main" },
    { "quantizeLinear", "main" },
    { "quantizeLinearTyped", "main" },
    { "rMSNorm", "main" },
    { "reLU", "main" },
    { "reduce", "main" },
    { "requantizeLinearTyped", "main" },
    { "resize", "main" },
    { "resizeNearestTyped", "main" },
    { "rowIndexTransfer", "main" },
    { "sDPA", "main" },
    { "siLU", "main" },
    { "sigmoid", "main" },
    { "slice", "main" },
    { "sliceNd", "main" },
    { "softmax", "main" },
    { "spatialSoftargmaxY", "main" },
    { "split", "main" },
    { "sub", "main" },
    { "tanh", "main" },
    { "transposeTyped", "main" },
    { "typedControl32Native", "main" },
    { "upsample2x", "main" },
    { "where", "main" },
    { "where32Native", "main" },
    { "whereTyped", "main" },
};

static const VxShaderInterface vx_shader_interface[VX_SHADER_COUNT] = {
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 4, 3, 4, {64, 1, 1}, 0 }, /* shaders/inference/add.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 8, {64, 1, 1}, 0 }, /* shaders/inference/add3Relu.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 4, 3, 8, {64, 1, 1}, 0 }, /* shaders/inference/addRelu.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 16, {64, 1, 1}, 0 }, /* shaders/inference/argMaxF32.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 16, {64, 1, 1}, 0 }, /* shaders/inference/argMaxF32I32Native.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 16, {64, 1, 1}, 0 }, /* shaders/inference/argMaxI32.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 16, {64, 1, 1}, 0 }, /* shaders/inference/argMaxI8.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 48, {8, 8, 1}, 0 }, /* shaders/inference/averagePool2D.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 4, 255, 0, {8, 8, 1}, 0 }, /* shaders/inference/batchMatMul.wgsl */
    { {0, 1, 2, 3, 4, 5, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 6, 32, 6, 20, {64, 1, 1}, 0 }, /* shaders/inference/batchNorm2D.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 4, 3, 20, {64, 1, 1}, 0 }, /* shaders/inference/binaryBroadcast.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 4, 255, 0, {64, 1, 1}, 0 }, /* shaders/inference/broadcastBinary.wgsl#broadcastAdd */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 4, 255, 0, {64, 1, 1}, 0 }, /* shaders/inference/broadcastBinary.wgsl#broadcastAddReLU */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 4, 255, 0, {64, 1, 1}, 0 }, /* shaders/inference/broadcastBinary.wgsl#broadcastAddReLU6 */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 4, 255, 0, {64, 1, 1}, 0 }, /* shaders/inference/broadcastBinaryNative.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 4, 255, 0, {64, 1, 1}, 0 }, /* shaders/inference/broadcastBinary.wgsl#broadcastDiv */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 4, 255, 0, {64, 1, 1}, 0 }, /* shaders/inference/broadcastBinary.wgsl#broadcastMul */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 4, 255, 0, {64, 1, 1}, 0 }, /* shaders/inference/broadcastBinary.wgsl#broadcastSub */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 16, {64, 1, 1}, 0 }, /* shaders/inference/cast.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 12, {64, 1, 1}, 0 }, /* shaders/inference/clip.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 48, {64, 1, 1}, 0 }, /* shaders/inference/clipTyped.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 4, 255, 0, {64, 1, 1}, 0 }, /* shaders/inference/compareI32.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 4, 3, 8, {64, 1, 1}, 0 }, /* shaders/inference/concat2.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 32, {64, 1, 1}, 0 }, /* shaders/inference/concatCopy.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 32, {64, 1, 1}, 0 }, /* shaders/inference/concatCopy32.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 32, {64, 1, 1}, 0 }, /* shaders/inference/concatCopy32Native.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 32, {64, 1, 1}, 0 }, /* shaders/inference/concatCopyTyped.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 32, {64, 1, 1}, 0 }, /* shaders/inference/concatSigmoidCopy.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 48, {64, 1, 1}, 0 }, /* shaders/inference/conv1D.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 68, {8, 8, 1}, 0 }, /* shaders/inference/conv2D.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 68, {8, 8, 1}, 0 }, /* shaders/inference/conv2DDepthwise4.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 68, {8, 8, 1}, 0 }, /* shaders/inference/conv2DDepthwise8.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 68, {8, 8, 1}, 0 }, /* shaders/inference/conv2DPointwise16.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 68, {8, 8, 1}, 4096 }, /* shaders/inference/conv2DPointwise16Tile.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 68, {8, 8, 1}, 0 }, /* shaders/inference/conv2DPointwise8.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 68, {8, 8, 1}, 0 }, /* shaders/inference/conv2DPointwise8Vec2.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 68, {8, 8, 1}, 0 }, /* shaders/inference/conv2DPointwise8Vec4.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 68, {8, 8, 1}, 0 }, /* shaders/inference/conv2DRegularC3Out16.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 68, {8, 8, 1}, 0 }, /* shaders/inference/conv2DRegularOut16.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 56, {8, 8, 1}, 0 }, /* shaders/inference/convTranspose2D.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 4, {64, 1, 1}, 0 }, /* shaders/inference/copy.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 16, {64, 1, 1}, 0 }, /* shaders/inference/copy32.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 16, {64, 1, 1}, 0 }, /* shaders/inference/copyTyped.wgsl */
    { {0, 1, 2, 3, 4, 5, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 6, 32, 6, 48, {64, 1, 1}, 0 }, /* shaders/inference/crossAttention.wgsl */
    { {0, 1, 2, 3, 4, 5, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 6, 32, 6, 48, {64, 1, 1}, 0 }, /* shaders/inference/crossAttentionF32.wgsl */
    { {0, 1, 2, 3, 4, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 5, 16, 5, 48, {64, 1, 1}, 0 }, /* shaders/inference/crossSDPA.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 4, 3, 24, {64, 1, 1}, 0 }, /* shaders/inference/decodeKeepMask.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 32, {64, 1, 1}, 0 }, /* shaders/inference/denseF32.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 8, {64, 1, 1}, 0 }, /* shaders/inference/dequantizeLinear.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 32, {64, 1, 1}, 0 }, /* shaders/inference/dequantizeLinearTyped.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 4, 3, 20, {64, 1, 1}, 0 }, /* shaders/inference/div.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 4, {64, 1, 1}, 0 }, /* shaders/inference/elementwise.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 4, 3, 16, {64, 1, 1}, 0 }, /* shaders/inference/embedding.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 80, {64, 1, 1}, 0 }, /* shaders/inference/expand.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 80, {64, 1, 1}, 0 }, /* shaders/inference/expandTyped.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 16, {64, 1, 1}, 0 }, /* shaders/inference/gELU.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 4, 3, 20, {64, 1, 1}, 0 }, /* shaders/inference/gather.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 4, 3, 80, {64, 1, 1}, 0 }, /* shaders/inference/gatherElements.wgsl */
    { {0, 1, 2, 4, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 4, 3, 96, {64, 1, 1}, 0 }, /* shaders/inference/gatherInt32.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 2, 255, 0, {64, 1, 1}, 0 }, /* shaders/inference/generalTranspose.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 16, {64, 1, 1}, 0 }, /* shaders/inference/globalAveragePool.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 32, {64, 1, 1}, 0 }, /* shaders/inference/groupNorm.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 4, {64, 1, 1}, 0 }, /* shaders/inference/hardSigmoid.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 4, {64, 1, 1}, 0 }, /* shaders/inference/hardSwish.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 16, {64, 1, 1}, 0 }, /* shaders/inference/incrementalRowByteCopy.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 16, {64, 1, 1}, 0 }, /* shaders/inference/interp1D.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 16, {64, 1, 1}, 0 }, /* shaders/inference/layerNorm.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 8, {64, 1, 1}, 0 }, /* shaders/inference/leakyReLU.wgsl */
    { {0, 1, 2, 3, 4, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 5, 16, 5, 12, {64, 1, 1}, 0 }, /* shaders/inference/linearF32.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 12, {64, 1, 1}, 0 }, /* shaders/inference/linearF32RowMajor.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 12, {8, 8, 1}, 2048 }, /* shaders/inference/linearF32RowMajorTiled.wgsl */
    { {0, 1, 2, 3, 4, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 5, 16, 5, 12, {8, 8, 1}, 2048 }, /* shaders/inference/linearF32Tiled.wgsl */
    { {0, 1, 2, 3, 4, 5, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 6, 32, 6, 32, {64, 1, 1}, 0 }, /* shaders/inference/linearInt8.wgsl */
    { {0, 1, 2, 3, 4, 5, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 6, 32, 6, 32, {8, 8, 1}, 2048 }, /* shaders/inference/linearInt8Tiled.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 8, {64, 1, 1}, 0 }, /* shaders/inference/logSoftmax.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 28, {64, 1, 1}, 0 }, /* shaders/inference/loraApply.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 48, {8, 8, 1}, 0 }, /* shaders/inference/maxPool2D.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 64, {64, 1, 1}, 0 }, /* shaders/inference/maxPool2DTyped.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 16, {64, 1, 1}, 0 }, /* shaders/inference/meanHeight.wgsl */
    { {0, 1, 2, 3, 4, 5, 7, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 7, 32, 6, 28, {64, 1, 1}, 0 }, /* shaders/inference/moeLinear.wgsl */
    { {0, 1, 2, 3, 4, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 5, 24, 5, 28, {64, 1, 1}, 0 }, /* shaders/inference/moeRouter.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 4, 3, 20, {64, 1, 1}, 0 }, /* shaders/inference/mul.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 4, 3, 28, {1, 1, 1}, 0 }, /* shaders/inference/nonMaxSuppression.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 16, {64, 1, 1}, 0 }, /* shaders/inference/notI32.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 4, 3, 16, {64, 1, 1}, 0 }, /* shaders/inference/pReLU.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 64, {64, 1, 1}, 0 }, /* shaders/inference/pad.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 16, {64, 1, 1}, 0 }, /* shaders/inference/profileX.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 16, {64, 1, 1}, 0 }, /* shaders/inference/profileY.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 4, 3, 48, {64, 1, 1}, 0 }, /* shaders/inference/qAdd.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 16, {64, 1, 1}, 0 }, /* shaders/inference/qArgMaxInt8.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 4, 4, 64, {64, 1, 1}, 0 }, /* shaders/inference/qBatchMatMul.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 4, 4, 64, {64, 1, 1}, 0 }, /* shaders/inference/qBatchMatMulDot.wgsl */
    { {0, 1, 2, 3, 4, 5, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 6, 32, 6, 112, {64, 1, 1}, 0 }, /* shaders/inference/qConv2DInt8.wgsl */
    { {0, 1, 2, 3, 4, 5, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 6, 32, 6, 112, {8, 4, 1}, 1152 }, /* shaders/inference/qConv2DInt8DotTiled.wgsl */
    { {0, 1, 2, 3, 4, 5, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 6, 32, 6, 112, {8, 4, 1}, 128 }, /* shaders/inference/qConv2DInt8Tiled.wgsl */
    { {0, 1, 2, 3, 4, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 5, 16, 5, 32, {64, 1, 1}, 0 }, /* shaders/inference/qEmbeddingInt8.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 48, {64, 1, 1}, 0 }, /* shaders/inference/qGELUInt8.wgsl */
    { {0, 1, 2, 3, 4, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 5, 16, 5, 64, {64, 1, 1}, 0 }, /* shaders/inference/qGroupNormApply.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 64, {64, 1, 1}, 528 }, /* shaders/inference/qGroupNormStats.wgsl */
    { {0, 1, 2, 3, 4, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 5, 16, 5, 48, {64, 1, 1}, 0 }, /* shaders/inference/qLayerNormApply.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 48, {64, 1, 1}, 528 }, /* shaders/inference/qLayerNormStats.wgsl */
    { {0, 1, 2, 3, 4, 5, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 6, 32, 6, 64, {64, 1, 1}, 0 }, /* shaders/inference/qLinearInt8.wgsl */
    { {0, 1, 2, 3, 4, 5, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 6, 32, 6, 64, {64, 1, 1}, 0 }, /* shaders/inference/qLinearInt8Dot.wgsl */
    { {0, 1, 2, 3, 4, 5, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 6, 32, 6, 64, {8, 8, 1}, 640 }, /* shaders/inference/qLinearInt8DotTiled.wgsl */
    { {0, 1, 2, 3, 4, 5, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 6, 32, 6, 64, {8, 8, 1}, 2560 }, /* shaders/inference/qLinearInt8Tiled.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 4, 3, 48, {64, 1, 1}, 0 }, /* shaders/inference/qMaskedMeanInt8.wgsl */
    { {0, 1, 2, 3, 4, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 5, 16, 5, 80, {32, 1, 1}, 8576 }, /* shaders/inference/qSDPAInt8.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 48, {64, 1, 1}, 0 }, /* shaders/inference/qSiLUInt8.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 32, {64, 1, 1}, 0 }, /* shaders/inference/quantizeLinear.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 16, {64, 1, 1}, 0 }, /* shaders/inference/quantizeLinearTyped.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 4, 3, 12, {64, 1, 1}, 0 }, /* shaders/inference/rMSNorm.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 4, {64, 1, 1}, 0 }, /* shaders/inference/reLU.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 12, {64, 1, 1}, 0 }, /* shaders/inference/reduce.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 48, {64, 1, 1}, 0 }, /* shaders/inference/requantizeLinearTyped.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 28, {8, 8, 1}, 0 }, /* shaders/inference/resize.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 32, {64, 1, 1}, 0 }, /* shaders/inference/resizeNearestTyped.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 4, 3, 16, {64, 1, 1}, 0 }, /* shaders/inference/rowIndexTransfer.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 4, 3, 32, {64, 1, 1}, 0 }, /* shaders/inference/sDPA.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 4, {64, 1, 1}, 0 }, /* shaders/inference/siLU.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 4, {64, 1, 1}, 0 }, /* shaders/inference/sigmoid.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 64, {64, 1, 1}, 0 }, /* shaders/inference/slice.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 144, {64, 1, 1}, 0 }, /* shaders/inference/sliceNd.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 8, {64, 1, 1}, 0 }, /* shaders/inference/softmax.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 16, {64, 1, 1}, 0 }, /* shaders/inference/spatialSoftargmaxY.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 20, {64, 1, 1}, 0 }, /* shaders/inference/split.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 4, 3, 20, {64, 1, 1}, 0 }, /* shaders/inference/sub.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 4, {64, 1, 1}, 0 }, /* shaders/inference/tanh.wgsl */
    { {0, 1, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 3, 2, 255, 0, {64, 1, 1}, 0 }, /* shaders/inference/transposeTyped.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 4, 255, 0, {64, 1, 1}, 0 }, /* shaders/inference/typedControl32Native.wgsl */
    { {0, 1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 2, 2, 2, 16, {8, 8, 1}, 0 }, /* shaders/inference/upsample2x.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 4, {64, 1, 1}, 0 }, /* shaders/inference/where.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 16, {64, 1, 1}, 0 }, /* shaders/inference/where32Native.wgsl */
    { {0, 1, 2, 3, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255}, 4, 8, 4, 16, {64, 1, 1}, 0 }, /* shaders/inference/whereTyped.wgsl */
};

#if VOLVOXAI_ENABLE_TRAINING && VOLVOXAI_ENABLE_WEBGPU
static const struct { const char* name; const char* entry; uint32_t id; }
vx_training_shader_entries[] = {

};
#endif

#define VX_SHADER_INFERENCE_ADD UINT32_C(0)
#define VX_SHADER_INFERENCE_ADD3_RELU UINT32_C(1)
#define VX_SHADER_INFERENCE_ADD_RELU UINT32_C(2)
#define VX_SHADER_INFERENCE_ARG_MAX_F32 UINT32_C(3)
#define VX_SHADER_INFERENCE_ARG_MAX_F32_I32_NATIVE UINT32_C(4)
#define VX_SHADER_INFERENCE_ARG_MAX_I32 UINT32_C(5)
#define VX_SHADER_INFERENCE_ARG_MAX_I8 UINT32_C(6)
#define VX_SHADER_INFERENCE_AVERAGE_POOL2_D UINT32_C(7)
#define VX_SHADER_INFERENCE_BATCH_MAT_MUL UINT32_C(8)
#define VX_SHADER_INFERENCE_BATCH_NORM2_D UINT32_C(9)
#define VX_SHADER_INFERENCE_BINARY_BROADCAST UINT32_C(10)
#define VX_SHADER_INFERENCE_BROADCAST_ADD UINT32_C(11)
#define VX_SHADER_INFERENCE_BROADCAST_ADD_RE_LU UINT32_C(12)
#define VX_SHADER_INFERENCE_BROADCAST_ADD_RE_LU6 UINT32_C(13)
#define VX_SHADER_INFERENCE_BROADCAST_BINARY_NATIVE UINT32_C(14)
#define VX_SHADER_INFERENCE_BROADCAST_DIV UINT32_C(15)
#define VX_SHADER_INFERENCE_BROADCAST_MUL UINT32_C(16)
#define VX_SHADER_INFERENCE_BROADCAST_SUB UINT32_C(17)
#define VX_SHADER_INFERENCE_CAST UINT32_C(18)
#define VX_SHADER_INFERENCE_CLIP UINT32_C(19)
#define VX_SHADER_INFERENCE_CLIP_TYPED UINT32_C(20)
#define VX_SHADER_INFERENCE_COMPARE_I32 UINT32_C(21)
#define VX_SHADER_INFERENCE_CONCAT2 UINT32_C(22)
#define VX_SHADER_INFERENCE_CONCAT_COPY UINT32_C(23)
#define VX_SHADER_INFERENCE_CONCAT_COPY32 UINT32_C(24)
#define VX_SHADER_INFERENCE_CONCAT_COPY32_NATIVE UINT32_C(25)
#define VX_SHADER_INFERENCE_CONCAT_COPY_TYPED UINT32_C(26)
#define VX_SHADER_INFERENCE_CONCAT_SIGMOID_COPY UINT32_C(27)
#define VX_SHADER_INFERENCE_CONV1_D UINT32_C(28)
#define VX_SHADER_INFERENCE_CONV2_D UINT32_C(29)
#define VX_SHADER_INFERENCE_CONV2_D_DEPTHWISE4 UINT32_C(30)
#define VX_SHADER_INFERENCE_CONV2_D_DEPTHWISE8 UINT32_C(31)
#define VX_SHADER_INFERENCE_CONV2_D_POINTWISE16 UINT32_C(32)
#define VX_SHADER_INFERENCE_CONV2_D_POINTWISE16_TILE UINT32_C(33)
#define VX_SHADER_INFERENCE_CONV2_D_POINTWISE8 UINT32_C(34)
#define VX_SHADER_INFERENCE_CONV2_D_POINTWISE8_VEC2 UINT32_C(35)
#define VX_SHADER_INFERENCE_CONV2_D_POINTWISE8_VEC4 UINT32_C(36)
#define VX_SHADER_INFERENCE_CONV2_D_REGULAR_C3_OUT16 UINT32_C(37)
#define VX_SHADER_INFERENCE_CONV2_D_REGULAR_OUT16 UINT32_C(38)
#define VX_SHADER_INFERENCE_CONV_TRANSPOSE2_D UINT32_C(39)
#define VX_SHADER_INFERENCE_COPY UINT32_C(40)
#define VX_SHADER_INFERENCE_COPY32 UINT32_C(41)
#define VX_SHADER_INFERENCE_COPY_TYPED UINT32_C(42)
#define VX_SHADER_INFERENCE_CROSS_ATTENTION UINT32_C(43)
#define VX_SHADER_INFERENCE_CROSS_ATTENTION_F32 UINT32_C(44)
#define VX_SHADER_INFERENCE_CROSS_SDPA UINT32_C(45)
#define VX_SHADER_INFERENCE_DECODE_KEEP_MASK UINT32_C(46)
#define VX_SHADER_INFERENCE_DENSE_F32 UINT32_C(47)
#define VX_SHADER_INFERENCE_DEQUANTIZE_LINEAR UINT32_C(48)
#define VX_SHADER_INFERENCE_DEQUANTIZE_LINEAR_TYPED UINT32_C(49)
#define VX_SHADER_INFERENCE_DIV UINT32_C(50)
#define VX_SHADER_INFERENCE_ELEMENTWISE UINT32_C(51)
#define VX_SHADER_INFERENCE_EMBEDDING UINT32_C(52)
#define VX_SHADER_INFERENCE_EXPAND UINT32_C(53)
#define VX_SHADER_INFERENCE_EXPAND_TYPED UINT32_C(54)
#define VX_SHADER_INFERENCE_G_ELU UINT32_C(55)
#define VX_SHADER_INFERENCE_GATHER UINT32_C(56)
#define VX_SHADER_INFERENCE_GATHER_ELEMENTS UINT32_C(57)
#define VX_SHADER_INFERENCE_GATHER_INT32 UINT32_C(58)
#define VX_SHADER_INFERENCE_GENERAL_TRANSPOSE UINT32_C(59)
#define VX_SHADER_INFERENCE_GLOBAL_AVERAGE_POOL UINT32_C(60)
#define VX_SHADER_INFERENCE_GROUP_NORM UINT32_C(61)
#define VX_SHADER_INFERENCE_HARD_SIGMOID UINT32_C(62)
#define VX_SHADER_INFERENCE_HARD_SWISH UINT32_C(63)
#define VX_SHADER_INFERENCE_INCREMENTAL_ROW_BYTE_COPY UINT32_C(64)
#define VX_SHADER_INFERENCE_INTERP1_D UINT32_C(65)
#define VX_SHADER_INFERENCE_LAYER_NORM UINT32_C(66)
#define VX_SHADER_INFERENCE_LEAKY_RE_LU UINT32_C(67)
#define VX_SHADER_INFERENCE_LINEAR_F32 UINT32_C(68)
#define VX_SHADER_INFERENCE_LINEAR_F32_ROW_MAJOR UINT32_C(69)
#define VX_SHADER_INFERENCE_LINEAR_F32_ROW_MAJOR_TILED UINT32_C(70)
#define VX_SHADER_INFERENCE_LINEAR_F32_TILED UINT32_C(71)
#define VX_SHADER_INFERENCE_LINEAR_INT8 UINT32_C(72)
#define VX_SHADER_INFERENCE_LINEAR_INT8_TILED UINT32_C(73)
#define VX_SHADER_INFERENCE_LOG_SOFTMAX UINT32_C(74)
#define VX_SHADER_INFERENCE_LORA_APPLY UINT32_C(75)
#define VX_SHADER_INFERENCE_MAX_POOL2_D UINT32_C(76)
#define VX_SHADER_INFERENCE_MAX_POOL2_D_TYPED UINT32_C(77)
#define VX_SHADER_INFERENCE_MEAN_HEIGHT UINT32_C(78)
#define VX_SHADER_INFERENCE_MOE_LINEAR UINT32_C(79)
#define VX_SHADER_INFERENCE_MOE_ROUTER UINT32_C(80)
#define VX_SHADER_INFERENCE_MUL UINT32_C(81)
#define VX_SHADER_INFERENCE_NON_MAX_SUPPRESSION UINT32_C(82)
#define VX_SHADER_INFERENCE_NOT_I32 UINT32_C(83)
#define VX_SHADER_INFERENCE_P_RE_LU UINT32_C(84)
#define VX_SHADER_INFERENCE_PAD UINT32_C(85)
#define VX_SHADER_INFERENCE_PROFILE_X UINT32_C(86)
#define VX_SHADER_INFERENCE_PROFILE_Y UINT32_C(87)
#define VX_SHADER_INFERENCE_Q_ADD UINT32_C(88)
#define VX_SHADER_INFERENCE_Q_ARG_MAX_INT8 UINT32_C(89)
#define VX_SHADER_INFERENCE_Q_BATCH_MAT_MUL UINT32_C(90)
#define VX_SHADER_INFERENCE_Q_BATCH_MAT_MUL_DOT UINT32_C(91)
#define VX_SHADER_INFERENCE_Q_CONV2_D_INT8 UINT32_C(92)
#define VX_SHADER_INFERENCE_Q_CONV2_D_INT8_DOT_TILED UINT32_C(93)
#define VX_SHADER_INFERENCE_Q_CONV2_D_INT8_TILED UINT32_C(94)
#define VX_SHADER_INFERENCE_Q_EMBEDDING_INT8 UINT32_C(95)
#define VX_SHADER_INFERENCE_Q_GELU_INT8 UINT32_C(96)
#define VX_SHADER_INFERENCE_Q_GROUP_NORM_APPLY UINT32_C(97)
#define VX_SHADER_INFERENCE_Q_GROUP_NORM_STATS UINT32_C(98)
#define VX_SHADER_INFERENCE_Q_LAYER_NORM_APPLY UINT32_C(99)
#define VX_SHADER_INFERENCE_Q_LAYER_NORM_STATS UINT32_C(100)
#define VX_SHADER_INFERENCE_Q_LINEAR_INT8 UINT32_C(101)
#define VX_SHADER_INFERENCE_Q_LINEAR_INT8_DOT UINT32_C(102)
#define VX_SHADER_INFERENCE_Q_LINEAR_INT8_DOT_TILED UINT32_C(103)
#define VX_SHADER_INFERENCE_Q_LINEAR_INT8_TILED UINT32_C(104)
#define VX_SHADER_INFERENCE_Q_MASKED_MEAN_INT8 UINT32_C(105)
#define VX_SHADER_INFERENCE_Q_SDPA_INT8 UINT32_C(106)
#define VX_SHADER_INFERENCE_Q_SI_LU_INT8 UINT32_C(107)
#define VX_SHADER_INFERENCE_QUANTIZE_LINEAR UINT32_C(108)
#define VX_SHADER_INFERENCE_QUANTIZE_LINEAR_TYPED UINT32_C(109)
#define VX_SHADER_INFERENCE_R_MS_NORM UINT32_C(110)
#define VX_SHADER_INFERENCE_RE_LU UINT32_C(111)
#define VX_SHADER_INFERENCE_REDUCE UINT32_C(112)
#define VX_SHADER_INFERENCE_REQUANTIZE_LINEAR_TYPED UINT32_C(113)
#define VX_SHADER_INFERENCE_RESIZE UINT32_C(114)
#define VX_SHADER_INFERENCE_RESIZE_NEAREST_TYPED UINT32_C(115)
#define VX_SHADER_INFERENCE_ROW_INDEX_TRANSFER UINT32_C(116)
#define VX_SHADER_INFERENCE_S_DPA UINT32_C(117)
#define VX_SHADER_INFERENCE_SI_LU UINT32_C(118)
#define VX_SHADER_INFERENCE_SIGMOID UINT32_C(119)
#define VX_SHADER_INFERENCE_SLICE UINT32_C(120)
#define VX_SHADER_INFERENCE_SLICE_ND UINT32_C(121)
#define VX_SHADER_INFERENCE_SOFTMAX UINT32_C(122)
#define VX_SHADER_INFERENCE_SPATIAL_SOFTARGMAX_Y UINT32_C(123)
#define VX_SHADER_INFERENCE_SPLIT UINT32_C(124)
#define VX_SHADER_INFERENCE_SUB UINT32_C(125)
#define VX_SHADER_INFERENCE_TANH UINT32_C(126)
#define VX_SHADER_INFERENCE_TRANSPOSE_TYPED UINT32_C(127)
#define VX_SHADER_INFERENCE_TYPED_CONTROL32_NATIVE UINT32_C(128)
#define VX_SHADER_INFERENCE_UPSAMPLE2X UINT32_C(129)
#define VX_SHADER_INFERENCE_WHERE UINT32_C(130)
#define VX_SHADER_INFERENCE_WHERE32_NATIVE UINT32_C(131)
#define VX_SHADER_INFERENCE_WHERE_TYPED UINT32_C(132)

#endif
